databases:
  - name: cashup
    databaseName: cashup
    user: cashup_user

services:
  - type: web
    name: cashup
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cashup
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false